import 'package:audioplayers/audioplayers.dart';

/// Synthesized sound effects (assets/audio/*.wav, generated by
/// tools/gen_audio.py - no licensed assets).
class AudioManager {
  AudioManager({int poolSize = 6}) {
    for (var i = 0; i < poolSize; i++) {
      _pool.add(AudioPlayer()..setReleaseMode(ReleaseMode.stop));
    }
  }

  final List<AudioPlayer> _pool = [];
  int _cursor = 0;
  bool _soundOn = true;

  void setSoundEnabled(bool on) => _soundOn = on;

  Future<void> play(String name) async {
    if (!_soundOn) return;
    final player = _pool[_cursor % _pool.length];
    _cursor++;
    try {
      await player.stop();
      await player.play(AssetSource('audio/$name'));
    } catch (_) {
      // audio must never crash the game
    }
  }

  Future<void> click() => play('click.wav');

  Future<void> tick() => play('tick.wav');

  Future<void> pop() => play('pop.wav');

  Future<void> unscrew() => play('unscrew.wav');

  Future<void> metal() => play('metal.wav');

  Future<void> drop() => play('drop.wav');

  Future<void> heavy() => play('heavy.wav');

  Future<void> coin() => play('coin.wav');

  Future<void> error() => play('error.wav');

  Future<void> chime() => play('chime.wav');

  Future<void> victory() => play('victory.wav');

  Future<void> bump() => play('bump.wav');

  void dispose() {
    for (final p in _pool) {
      p.dispose();
    }
  }
}
